# Generated by Django 3.0.8 on 2020-07-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0004_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(default=0),
        ),
    ]
